name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '✨ Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
  - title: '🔧 Operations'
    label: 'ops'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  $CHANGES

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'ops'
    files:
      - '.github/*.yml'
      - '.github/workflows/*.yml'
      - '.gitignore'
      - 'tsconfig.json'
      - 'Dockerfile'